info:
  name: Update Notifications Settings (SMTP)
  type: http
  seq: 2

http:
  method: PUT
  url: "{{apiPath}}/environments/{{envID}}/notificationsSettings/emailDeliverySettings"
  body:
    type: json
    data: |-
      {
          "host": "email-smtp.amazonaws.com",
          "port": 465,
          "username": "smtp_username",
          "password": "{{password}}",
          "from": {
              "name": "from_name",
              "address": "from@pingidentity.com"
          },
          "replyTo": {
              "name": "reply_name",
              "address": "reply@pingidentity.com"
          }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Notifications Settings (SMTP)](https://developer.pingidentity.com/pingone-api/platform/notifications/notifications-settings-smtp/update-notifications-settings-smtp.html).
