info:
  name: Delete Application Role Assignment
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{apiPath}}/environments/{{envID}}/applications/{{appID}}/roleAssignments/{{roleAssignmentID}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Delete Application Role Assignment](https://developer.pingidentity.com/pingone-api/platform/applications/application-role-assignments/delete-application-role-assignment.html).
