info:
  name: Delete Application Resource
  type: http
  seq: 5

http:
  method: DELETE
  url: "{{apiPath}}/environments/{{envID}}/resources/{{resourceID}}/applicationResources/{{appResourceID}}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Delete Application Resource](https://developer.pingidentity.com/pingone-api/platform/resources/application-resources/delete-application-resource.html).
