info:
  name: Read All Environments
  type: http
  seq: 3

http:
  method: GET
  url: "{{apiPath}}/environments"
  params:
    - name: limit
      value: "1"
      type: query
      disabled: true
    - name: expand
      value: billOfMaterials
      type: query
      disabled: true
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Read All Environments](https://developer.pingidentity.com/pingone-api/platform/environments/read-all-environments.html).
