info:
  name: Update Environment Status
  type: http
  seq: 4

http:
  method: PUT
  url: "{{apiPath}}/environments/{{envID}}/status"
  body:
    type: json
    data: |-
      {
          "status": "DELETE_PENDING"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Environment Status](https://developer.pingidentity.com/pingone-api/platform/environments/update-environment-status.html).
