name: Production
color: "#4CAF50"
variables:
  - name: baseUrl
    value: https://jsonplaceholder.typicode.com
  - name: breweryUrl
    value: https://api.openbrewerydb.org/v1
  - name: dummyUrl
    value: https://dummyjson.com
  - name: weatherUrl
    value: https://api.open-meteo.com/v1
  - name: postId
    value: "1"
  - name: userId
    value: "1"
  - name: releaseStage
    value: production
