info:
  name: Update Recaptcha Configuration
  type: http
  seq: 2

http:
  method: PUT
  url: "{{apiPath}}/environments/{{envID}}/recaptchaV2Config"
  body:
    type: json
    data: |-
      {
          "siteKey": "{{recaptchaSiteKey}}",
          "secretKey": "{{recaptchaSecretKey}}"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Recaptcha Configuration](https://developer.pingidentity.com/pingone-api/platform/forms-recaptcha/update-recaptcha-configuration.html).
