info:
  name: Read All Application Attribute Mappings
  type: http
  seq: 2

http:
  method: GET
  url: "{{apiPath}}/environments/{{envID}}/applications/{{appID}}/attributes"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Read All Application Attribute Mappings](https://developer.pingidentity.com/pingone-api/platform/applications/application-attribute-mapping/read-all-application-attribute-mappings.html).
