info:
  name: Create Application (OIDC Protocol - PingFederate Worker App)
  type: http
  seq: 7

http:
  method: POST
  url: "{{apiPath}}/environments/{{envID}}/applications"
  params:
    - name: expand
      value: attributes
      type: query
      disabled: true
  body:
    type: json
    data: |-
      {
          "enabled": true,
          "name": "PingFed WORKER-App2",
          "description": "Test Description - PingFederate Worker App",
          "type": "WORKER",
          "protocol": "OPENID_CONNECT",
          "homePageUrl": "https://example.com/homePage",
          "loginPageUrl": "https://example.com/loginPage",
          "icon": {
              "id": "{{imageID}}",
              "href": "https://upload.image.org/image.jpg"
          },
          "tags": [
              "PING_FED_CONNECTION_INTEGRATION"
          ],
          "grantTypes": [
              "CLIENT_CREDENTIALS"
          ],
          "postLogoutRedirectUris": [
              "https://example.com/logout"
          ],
          "redirectUris": [
              "https://example.com"
          ],
          "tokenEndpointAuthMethod": "CLIENT_SECRET_BASIC",
          "pkceEnforcement": "OPTIONAL",
          "refreshTokenDuration": 86400,
          "refreshTokenRollingDuration": 86400
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        if (res.getStatus() == 201) {
            try {
                var jsonData = res.getBody();
            }
            catch (e) {
                console.log("There was an error parsing JSON ", e);
            }
            bru.setEnvVar("appID", jsonData.id);
            console.log("appID is now: " + bru.getEnvVar("appID"));
        }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Create Application (OIDC Protocol - PingFederate Worker App)](https://developer.pingidentity.com/pingone-api/platform/applications/applications-1/create-application-oidc-protocol---pingfederate-worker-app.html).
