info:
  name: Create Application (OIDC Protocol - Web App)
  type: http
  seq: 1

http:
  method: POST
  url: "{{apiPath}}/environments/{{envID}}/applications"
  params:
    - name: expand
      value: attributes
      type: query
      disabled: true
  body:
    type: json
    data: |-
      {
          "enabled": true,
          "name": "OIDC-Web-App",
          "description": "Test Description - OIDC App (Web)",
          "type": "WEB_APP",
          "protocol": "OPENID_CONNECT",
          "homePageUrl": "https://example.com/homePage",
          "loginPageUrl": "https://example.com/loginPage",
          "icon": {
              "id": "{{iconID}}",
              "href": "https://upload.image/image.jpg"
          },
          "grantTypes": [
              "AUTHORIZATION_CODE"
          ],
          "postLogoutRedirectUris": [
              "https://example.com/logout"
          ],
          "redirectUris": [
              "https://example.com"
          ],
          "responseTypes": [
              "CODE"
          ],
          "signing": {
              "keyRotationPolicy": {
                  "id": "{{krpID}}"
              }
          },
          "tokenEndpointAuthMethod": "CLIENT_SECRET_BASIC",
          "pkceEnforcement": "REQUIRED",
          "refreshTokenDuration": 86400,
          "refreshTokenRollingDuration": 86400
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        if (res.getStatus() == 201) {
            try {
                var jsonData = res.getBody();
            }
            catch (e) {
                console.log("There was an error parsing JSON ", e);
            }
            bru.setEnvVar("appID", jsonData.id);
            console.log("appID is now: " + bru.getEnvVar("appID"));
        }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Create Application (OIDC Protocol - Web App)](https://developer.pingidentity.com/pingone-api/platform/applications/applications-1/create-application-oidc-protocol---web-app.html).
