info:
  name: Update Application (SAML)
  type: http
  seq: 15

http:
  method: PUT
  url: "{{apiPath}}/environments/{{envID}}/applications/{{appID}}"
  body:
    type: json
    data: |-
      {
          "name": "UPDATED_{{$timestamp}}",
          "description": "this is my UPDATED client",
          "enabled": false,
          "type": "WEB_APP",
          "protocol": "SAML",
          "assertionDuration": 60,
          "acsUrls": [
              "https://example.com"
          ],
          "sloResponseEndpoint": "https://example.com",
          "spEntityId": "test",
          "nameIdFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Application (SAML)](https://developer.pingidentity.com/pingone-api/platform/applications/applications-1/update-application-saml.html).
