info:
  name: Update Application (OIDC)
  type: http
  seq: 14

http:
  method: PUT
  url: "{{apiPath}}/environments/{{envID}}/applications/{{appID}}"
  body:
    type: json
    data: |-
      {
          "name": "AppName",
          "description": "This is my UPDATED app description",
          "protocol": "OPENID_CONNECT",
          "type": "WEB_APP"
          }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Application (OIDC)](https://developer.pingidentity.com/pingone-api/platform/applications/applications-1/update-application-oidc.html).
