info:
  name: Create originKey values for domains
  type: http
  seq: 2
  tags:
    - Utility

http:
  method: POST
  url: "{{baseUrl}}/originKeys"
  headers:
    - name: Idempotency-Key
      value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
      description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
  body:
    type: json
    data: |-
      {
        "originDomains": [
          "https://www.your-domain1.com",
          "https://www.your-domain2.com",
          "https://www.your-domain3.com"
        ]
      }
  auth:
    type: basic
    username: "{{username}}"
    password: "{{password}}"

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
  forwardAuthorizationHeader: false

examples:
  - name: Example response for request 'basic'
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 200
      statusText: OK
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "originKeys": {
              "https://www.your-domain1.com": "pub.v2.8116178901076090.aHR0cHM6Ly93d3cueW91ci1kb21haW4xLmNvbQ.pvbYlrXz0ICP4kwMJXDGDLVMqALhwXr1MSRjT-fkhvw",
              "https://www.your-domain3.com": "pub.v2.8116178901076090.aHR0cHM6Ly93d3cueW91ci1kb21haW4zLmNvbQ.FrTpVz7_RzAywKasM0kXCRoMfoMkKIKaxjFymRGORIc",
              "https://www.your-domain2.com": "pub.v2.8116178901076090.aHR0cHM6Ly93d3cueW91ci1kb21haW4yLmNvbQ.LdN9kvJ35fYFFiBSJA4idMnwwxJ5_yXpeNS__Ap5wkg"
            }
          }
  - name: Response code 400. Bad request. (Get origin keys)
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 400
      statusText: Bad Request
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 400,
            "errorCode": "702",
            "message": "Unexpected input: \", expected: }",
            "errorType": "validation"
          }
  - name: Response code 401. Unauthorized. (Get origin keys)
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 401
      statusText: Unauthorized
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 401,
            "errorCode": "000",
            "message": "HTTP Status Response - Unauthorized",
            "errorType": "security"
          }
  - name: Response code 403. Forbidden. (Get origin keys)
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 403
      statusText: Forbidden
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 403,
            "errorCode": "901",
            "message": "Invalid Merchant Account",
            "errorType": "security",
            "pspReference": "881611827877203B"
          }
  - name: Response code 422. Unprocessable entity. (Get origin keys)
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 422
      statusText: Unprocessable Entity
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 422,
            "errorCode": "14_030",
            "message": "Return URL is missing.",
            "errorType": "validation",
            "pspReference": "8816118280275544"
          }
  - name: Response code 500. Internal server error. (Get origin keys)
    request:
      url: "{{baseUrl}}/originKeys"
      method: POST
      headers:
        - name: Idempotency-Key
          value: 37ca9c97-d1d1-4c62-89e8-706891a563ed
          description: A unique identifier for the message with a maximum of 64 characters (we recommend a UUID).
      body:
        type: json
        data: |-
          {
            "originDomains": [
              "https://www.your-domain1.com",
              "https://www.your-domain2.com",
              "https://www.your-domain3.com"
            ]
          }
    response:
      status: 500
      statusText: Internal Server Error
      headers:
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
            "status": 500,
            "errorCode": "905",
            "message": "Payment details are not supported",
            "errorType": "configuration",
            "pspReference": "8516091485743033"
          }

docs: |-
  This operation takes the origin domains and returns a JSON object containing the corresponding origin keys for the domains. 
  > If you're still using origin key for your Web Drop-in or Components integration, we recommend [switching to client key](https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key). This allows you to use a single key for all origins, add or remove origins without generating a new key, and detect the card type from the number entered in your payment form. 
