info:
  name: Update Application Secret
  type: http
  seq: 1

http:
  method: POST
  url: "{{apiPath}}/environments/{{envID}}/applications/{{appID}}/secret"
  body:
    type: json
    data: |-
      {
          "previous": {
              "expiresAt": "2024-01-02T13:54:34.487Z"
          }
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        if (res.getStatus() == 200) {
            try {
                var jsonData = res.getBody();
            }
            catch (e) {
                console.log("There was an error parsing JSON ", e);
            }
            bru.setEnvVar("appSecret", jsonData.secret);
            console.log("appSecret is now: " + bru.getEnvVar("appSecret"));
        }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Update Application Secret](https://developer.pingidentity.com/pingone-api/platform/applications/application-secret/update-application-secret.html).
