info:
  name: Create Phone Delivery Settings (Twilio)
  type: http
  seq: 5

http:
  method: POST
  url: "{{apiPath}}/environments/{{envID}}/notificationsSettings/phoneDeliverySettings"
  body:
    type: json
    data: |-
      {
        "sid": "exampleSid",
        "authToken": "exampleAuthToken",
        "provider": "CUSTOM_TWILIO"
      }
  auth: inherit

runtime:
  scripts:
    - type: after-response
      code: |-
        if (res.getStatus() == 201) {
            try {
                var jsonData = res.getBody();
            }
            catch (e) {
                console.log("There was an error parsing JSON ", e);
            }
            bru.setEnvVar("phoneDeliverySettingsId", jsonData.id);
            console.log("phoneDeliverySettingsId is now: " + bru.getEnvVar("phoneDeliverySettingsId"));
        }

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Create Phone Delivery Settings (Twilio)](https://developer.pingidentity.com/pingone-api/platform/notifications/phone-delivery-settings/create-phone-delivery-settings-twilio.html).
