info:
  name: Delete Notifications Settings
  type: http
  seq: 3

http:
  method: DELETE
  url: "{{apiPath}}/environments/{{envID}}/notificationsSettings"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: This PingOne collection contains only the requests without documentation. For the official Platform SSO APIs documentation, see [Delete Notifications Settings](https://developer.pingidentity.com/pingone-api/platform/notifications/notifications-settings/delete-notifications-settings.html).
